# Generated by Django 2.2.2 on 2019-06-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fubar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.TextField()),
                ('retail_sales_volume', models.FloatField(default=0)),
                ('retail_price', models.FloatField(default=0)),
                ('acv_distribution', models.FloatField(default=0)),
                ('competition', models.FloatField(default=0)),
                ('edlp', models.FloatField(default=0)),
                ('trade_any_promo', models.FloatField(default=0)),
                ('tv', models.FloatField(default=0)),
                ('online_display', models.FloatField(default=0)),
                ('preroll_video', models.FloatField(default=0)),
                ('paid_search', models.FloatField(default=0)),
                ('public_relations', models.FloatField(default=0)),
                ('fsi', models.FloatField(default=0)),
                ('digital_coupon', models.FloatField(default=0)),
                ('shopper_marketing', models.FloatField(default=0)),
            ],
        ),
    ]
