# Generated by Django 2.2.2 on 2019-06-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='acv_distribution',
            new_name='Acv_Distribution',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='competition',
            new_name='Competition',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='digital_coupon',
            new_name='Digital_Coupon',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='edlp',
            new_name='Edlp',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='fsi',
            new_name='Fsi',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='online_display',
            new_name='Online_Display',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='paid_search',
            new_name='Paid_Search',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='preroll_video',
            new_name='Preroll_Video',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='public_relations',
            new_name='Print_Ad',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='retail_price',
            new_name='Public_Relations',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='retail_sales_volume',
            new_name='Retail_Price',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='shopper_marketing',
            new_name='Retail_Sales_Volume',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='trade_any_promo',
            new_name='Shopper_Marketing',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='tv',
            new_name='Trade_Any_Promo',
        ),
        migrations.RemoveField(
            model_name='row',
            name='observation_date',
        ),
        migrations.AddField(
            model_name='row',
            name='Observation_Date',
            field=models.CharField(default=0.09090909090909091, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='Tv',
            field=models.FloatField(default=0),
        ),
    ]
