# Generated by Django 2.2.2 on 2019-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_auto_20190626_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='Observation_Date',
            field=models.CharField(max_length=100),
        ),
    ]
