# Generated by Django 2.2.2 on 2019-07-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_auto_20190630_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='Acv_Distribution',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Competition',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Digital_Coupon',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Edlp',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Fsi',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Online_Display',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Paid_Search',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Preroll_Video',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Print_Ad',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Public_Relations',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Retail_Price',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Retail_Sales_Volume',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Shopper_Marketing',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Trade_Any_Promo',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='row',
            name='Tv',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
