# Generated by Django 2.2.2 on 2019-07-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0004_auto_20190630_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
