# Generated by Django 2.2.2 on 2019-07-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0006_auto_20190630_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='Acv_Distribution',
            new_name='A_D',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Competition',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Digital_Coupon',
            new_name='D_C',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Edlp',
            new_name='E',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Fsi',
            new_name='F',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Observation_Date',
            new_name='O_D',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Online_Display',
            new_name='O_Di',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Paid_Search',
            new_name='P_A',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Preroll_Video',
            new_name='P_R',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Print_Ad',
            new_name='P_S',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Public_Relations',
            new_name='P_V',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Retail_Price',
            new_name='R_P',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Retail_Sales_Volume',
            new_name='R_S_V',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Shopper_Marketing',
            new_name='S_M',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Trade_Any_Promo',
            new_name='T',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='Tv',
            new_name='T_A_P',
        ),
    ]
