# Generated by Django 2.2.2 on 2019-07-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0007_auto_20190630_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='A_D',
            new_name='Acv_Distribution',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='C',
            new_name='Competition',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='D_C',
            new_name='Digital_Coupon',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='E',
            new_name='Edlp',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='F',
            new_name='Fsi',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='O_D',
            new_name='Observation_Date',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='O_Di',
            new_name='Online_Display',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='P_A',
            new_name='Paid_Search',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='P_R',
            new_name='Preroll_Video',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='P_S',
            new_name='Print_Ad',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='P_V',
            new_name='Public_Relations',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='R_P',
            new_name='Retail_Price',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='R_S_V',
            new_name='Retail_Sales_Volume',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='S_M',
            new_name='Shopper_Marketing',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='T',
            new_name='Trade_Any_Promo',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='T_A_P',
            new_name='Tv',
        ),
    ]
